config/routes.rb
Rails.application.routes.draw do
  root "planets#index"
  resources :planets do 
    resources :reviews
  end

end

app/models/planet.rb
class Planet < ActiveRecord::Base
  has_many :reviews
  
  def average_rating
    ratings = self.reviews.map{|r| r["rating"]}
    average = (ratings.reduce(:+)/ratings.size.to_f).round(1)
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :planet
  validates :rating, :title, :author_name, :body, presence: true
  validates :body, length: {minimum: 20}
  validates :rating, inclusion: {in: (1..5)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController

  def index
    @planets = Planet.all
    @sorted = false
    if params[:sort_by]
      @sorted = true
      @planets = sorted_list(@planets, params[:sort_by])
    end
  end

  def show
    @planet = Planet.find(params[:id])
    @review = Review.new
    @review.planet_id = @planet.id
  end

  private

  def sorted_list(planets, sort_by)
    case sort_by
    when "top_rated"
      planets.order(average_rating: :desc)
    when "deserts"
      planets.select{|p| p.terrain.split(", ").include?("desert")}
    when 'forests'
      planets.select{|p| p.terrain.split(", ").include?("forests")}
    when 'mountains'
      planets.select{|p| p.terrain.split(", ").include?("mountains")}
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @planet = Planet.find(params[:planet_id])
    @review = Review.new
    @review.planet_id = @planet.id
  end

  def create
    @review = Review.new(review_params)
    @review.planet_id = params[:planet_id]
    @review.rating = params[:rating]

    if @review.save
      redirect_to planet_path(@review.planet)
    else
      @planet = Planet.find(params[:planet_id])
      render :new
   end
  end

  def review_params
    params.require(:review).permit(:author_name, :body, :rating, :title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Swapi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/planets/_review.html.erb
<div>
  <h4>"<%= review.title %>"</h4>
  <h5>Review by <%= review.author_name %></h5>
  <p>Rating: <%= review.rating %></p>
  <p><%= review.body %></p>
</div>

app/views/planets/index.html.erb
<h1>Welcome to Star Wars Tripadvisor!</h1>
<h2>Your destination for all your galactic travels</h2>
<h3>Choose from a planet below, or choose from one of our filters:</h3>
<%= link_to "Top Rated", root_path(sort_by: "top_rated")%>
<%= link_to "Deserts", root_path(sort_by: "deserts")%>
<%= link_to "Forests", root_path(sort_by: "forests")%>
<%= link_to "Mountains", root_path(sort_by: "mountains")%>
<% if @sorted %>
  <%= link_to "Show all", root_path%>
<% end %>

<table style="border-spacing: 15px">
  <tr>
    <th>Desintation</th>
    <th>Average Rating</th>
  </tr>
  <% @planets.each do |planet| %>
  <tr>
    <td><%= link_to planet.name, planet_path(planet) %></td>
    <td><%= planet.average_rating %></td>
  </tr>
  <% end %>
</table>

app/views/planets/show.html.erb
<h2><%= link_to "Star Wars TripAdvisor", root_path %></h2>

<h1><%= @planet.name %></h1>
<ul>
  <li>Population: <%= number_to_human(@planet.population) %></li>
  <li>Climate: <%= @planet.climate %></li>
  <li>Terrain: <%= @planet.terrain %></li>
</ul>

<h3><%= link_to "Write a review", new_planet_review_path(@planet) %></h3>

<h3>Reviews (<%= @planet.reviews.size %>)</h3>
<%= render partial: 'planets/review', collection: @planet.reviews.order(created_at: :desc) %>

app/views/reviews/new.html.erb
<% if @review.errors.any? %>
  <h2><%= pluralize(@review.errors.count, "error") %> prohibited this reivew from being saved: </h2>
  <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<h2><%= link_to "Star Wars TripAdvisor", root_path %></h2>

<h3>Write a Review</h3>

<%= form_for [@planet, @review] do |f| %>
  <p>Your overall rating of this planet: </p>
    <%= radio_button_tag(:rating, 1) %>
    <%= label_tag(:rating_1, "1") %>
    <%= radio_button_tag(:rating, 2) %>
    <%= label_tag(:rating_2, "2") %>
    <%= radio_button_tag(:rating, 3) %>
    <%= label_tag(:rating_3, "3") %>
    <%= radio_button_tag(:rating, 4) %>
    <%= label_tag(:rating_4, "4") %>
    <%= radio_button_tag(:rating, 5) %>
    <%= label_tag(:rating_5, "5") %>
  <p>
    <%= f.label :title, "Title of your review" %><br />
    <%= f.text_field :title, placeholder: "Summarize your visit"%>
  </p>
  <p>
    <%= f.label :author_name, "Your Name" %><br />
    <%= f.text_field :author_name  %>
  </p>
  <p>
    <%= f.label :body, "Your Review" %><br />
    <%= f.text_area :body, placeholder: "Tell people about your experience" %>
  </p>
  <p>
    <%= f.submit 'Submit your review' %>
  </p>
<% end %>